version: "3.8"

services:
  flask-app:
    build: /backend_flask
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j_db7

  neo4j:
    image: neo4j:5.25
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4j_db7
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
